export const ACTIVITY_LOGS_CONTENT = {
  eyebrow: "Audit Trail",
  title: "Activity Logs",
  description: "Track every system action, inventory movement, and user change in one place.",
  searchPlaceholder: "Search actor, action, or item...",
  tableTitle: "Recent activity",
  countLabel: (count: number) => `${count} ${count === 1 ? "entry" : "entries"}`,
  stats: {
    total: "Total events",
    today: "Today",
    actors: "Active users",
    movements: "Borrows & returns",
  },
  actionFilters: {
    all: "All",
    create: "Created",
    update: "Updated",
    remove: "Archived / Deleted",
    borrow: "Borrowed",
    return: "Returned",
  },
  tableHeaders: ["Actor", "Action", "Item", "Status change", "When"],
  none: "None",
  noStatusChange: "No status change",
  footerHint: "Click any row to open the full log details.",
  empty: {
    title: "No logs found",
    description: "No activity matches your search or filter. Try a different term or filter.",
  },
  error: {
    title: "Couldn't load activity",
    description: "There was a problem fetching the activity history. Check your connection and try again.",
    refresh: "Try again",
  },
  pagination: {
    showing: "Showing",
    of: " of ",
    entries: " entries",
    prev: "Prev",
    next: "Next",
  },
} as const;
