export const ACTIVE_BORROWED_ITEMS_CONTENT = {
  eyebrow: "Manage Borrow Items",
  title: "Active Borrowed Items",
  description: "All items currently borrowed and not yet returned.",
  tableTitle: "Currently Out",
  liveLabel: "Live",
  countLabel: (count: number) => `${count} active borrow${count !== 1 ? "s" : ""}`,
  searchPlaceholder: "Search item, serial, or borrower...",
  stats: {
    active: "Active borrows",
    today: "Lent today",
    longHeld: "Out over 24 hours",
    borrowers: "Unique borrowers",
  },
  sort: {
    newest: "Newest",
    oldest: "Longest out",
  },
  tableHeaders: ["Item", "Borrower", "Room", "Lent At", "Time Out", "Remarks", ""],
  noTeacher: "No teacher",
  teacherPrefix: "Teacher:",
  longHeldBadge: "Over 24h",
  returnButton: "Return",
  returnButtonTitle: "Manually return this item",
  footerHint:
    "Click a row to view borrow details. Use Return to manually mark an item as returned. Rows held over 24 hours are highlighted.",
  empty: {
    title: "No active borrowed items",
    description: 'Items with "Borrowed" status will appear here.',
    searchTitle: "No matches found",
    searchDescription: "Try a different item name, serial number, or borrower.",
  },
  toast: {
    errorTitle: "Error",
    idNotFound: "Lent item ID not found",
    returnedTitle: "Item Returned",
    returnedMessage: (itemName: string) => `${itemName} has been returned successfully`,
    returnFailedTitle: "Return Failed",
    returnFailed: "Failed to return item",
  },
} as const;
