export const DASHBOARD_CONTENT = {
  title: "Dashboard",
  description: "Here's what's happening with your inventory today.",
  notifications: "Notifications",
  online: "Online",
  greetings: {
    morning: "Good morning",
    afternoon: "Good afternoon",
    evening: "Good evening",
  },
  activity: {
    title: "Borrowing Activity",
    description: "Items lent out over the last 7 days",
    totalLabel: "this week",
    today: "Today",
  },
  statusOverview: {
    title: "Status Overview",
    description: "borrow records by status",
    empty: "No borrow records yet.",
  },
  badges: {
    totalItems: "Total Items",
    categories: "Categories",
    activeUsers: "Active Users",
    totalBorrowed: "Total Borrowed",
  },
  recentBorrows: {
    title: "Recently Borrowed Items",
    description: "The 5 most recent active borrows",
    viewAll: "View all",
    empty: {
      title: "No borrowed items",
      description: "There are no active borrows at the moment.",
    },
  },
  tableHeaders: [
    "Item",
    "Borrower",
    "Room",
    "Lent At",
    "Status",
    "Remarks",
  ],
  returnModal: {
    title: "Return Item",
    instructions: {
      prefix: "Scan the",
      highlight: "item barcode",
      suffix: "to mark it as returned.",
    },
    placeholder: "Scan or enter item barcode",
    cancel: "Cancel",
    confirm: "Confirm Return",
    processing: "Processing...",
  },
  scanModal: {
    title: "Scan Lent Item",
    instructions: {
      prefix: "Scan the",
      highlight: "lent item barcode",
      suffix: "to view its details.",
    },
    placeholder: "Scan or enter lent item barcode",
    cancel: "Cancel",
    confirm: "Confirm",
  },
  errors: {
    barcodeRequired: "Please enter a barcode",
    lentBarcodeRequired: "Please enter a lent item barcode",
    invalidLentBarcode: "Invalid lent item barcode format. Expected format: LENT-YYYYMMDD-XXX",
    lentItemNotFound: "Lent item not found",
    invalidResponseFormat: "Invalid response format from server",
    invalidResponseStructure: "Invalid response structure from server",
    fetchLentItemFailed: "Failed to fetch lent item details",
  },
  toast: {
    returnedTitle: "Item Returned",
    returnedMessage: "Item returned successfully!",
    returnFailedTitle: "Return Failed",
    returnFailed: "Failed to return item",
    borrowedTitle: "Item Borrowed",
    borrowedMessage: "Item borrowed successfully!",
  },
} as const;
